services:
  db:
    image: postgres:16-alpine
    container_name: etl_postgres
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Mount sql folder for easy execution inside container if needed
      - ./sql:/docker-entrypoint-initdb.d
      # Mount data folder to access CSV from inside container
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etl_user -d etl_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
